# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meansunz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='upvotes',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votecomments',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meansunz.Comment'),
        ),
        migrations.AddField(
            model_name='votecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='votecomments',
            unique_together=set([('user', 'comment')]),
        ),
    ]
