# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meansunz', '0002_auto_20190321_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoteComments',
            new_name='VoteComment',
        ),
    ]
