# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meansunz', '0003_auto_20190316_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
    ]
