# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meansunz', '0003_auto_20190321_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='VotePost',
        ),
    ]
