# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meansunz', '0006_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=1026)),
                ('picture', models.ImageField(blank=True, upload_to='comment_image')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
