# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meansunz', '0005_auto_20190317_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meansunz.UserProfile'),
            preserve_default=False,
        ),
    ]
