# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meansunz', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meansunz.Post'),
            preserve_default=False,
        ),
    ]
