# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meansunz', '0008_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contents',
            new_name='content',
        ),
    ]
