# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meansunz', '0016_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='downvote',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='upvote',
        ),
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
