# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meansunz', '0018_remove_vote_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'post')]),
        ),
    ]
