# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meansunz', '0019_auto_20190321_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=0),
        ),
    ]
