# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meansunz', '0021_auto_20190321_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 21, 8, 3, 703949)),
        ),
    ]
